name: PR Checks

on: pull_request

jobs:
  Build:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Gradle Build
        run: ./gradlew build -x test
      - name: KTLint Check
        run: ./gradlew ktlintCheck
      - name: Unit Tests
        run: ./gradlew test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/build/test-results/test/*.xml"
